### ISSUE TITLE
WG21 P2071: Add support for named Unicode character escapes

### ISSUE THREAD

**Issue by tahonermann** [sg16-unicode/sg16#15]
The C and C++ standards currently specify `\uXXXX` and `\UXXXXXXXX` in [[lex.charset]/2](http://eel.is/c++draft/lex.charset#2).  Perl [1] and Python [2] support named character escapes of the form `\N{NAME}`.

Support for named escape sequences would avoid the desire to write C++ code as follows:
```
auto s = u8"\u1235"; // {ETHIOPIC SYLLABLE SEE}
```

(Note: Oops!  That's the wrong name for that code point value!)

Better:
```
auto s = u8"\N{ETHIOPIC SYLLABLE SEE}";
```

\[1]: https://perldoc.perl.org/perluniintro.html#Creating-Unicode
\[2]: https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals

**Comment by tahonermann** [comment]
From a grammar stand point, I expect we would modify [[lex.charset]/2](http://eel.is/c++draft/lex.charset#2) as follows (assuming we stick with `\N{NAME}`):
```
universal-character-name:
	\u hex-quad
	\U hex-quad hex-quad
	\N { c-char-sequence }
```

**Comment by mzeren-vmw** [comment]
+1

**Comment by tahonermann** [comment]
> Would you support sequences? http://www.unicode.org/reports/tr34/

A very reasonable question for which I have no specific answer.  What would you like the answer to be?  Would they be well-formed in character literals?  I think yes, but with implementation defined behavior for the ordinary/wide character encodings and ill-formed in u8/u/U character literals.

**Comment by rmartinho** [comment]
I think ultimately we want to support named sequences, well-formed and well defined everywhere. Names and formal aliases are the bare minimum, but named sequences are a really nice to have

**Comment by rmartinho** [comment]
My idea is to define `\N{NAME}` as being equivalent to the sequence of `\UNNNNNNNN` that corresponds to NAME.

**Comment by jfbastien** [comment]
> A very reasonable question for which I have no specific answer. What would you like the answer to be?

Seems nice to have in the same paper.

> Would they be well-formed in character literals? I think yes, but with implementation defined behavior for the ordinary/wide character encodings and ill-formed in u8/u/U character literals.

That sounds right.


I assume an implementation would use the Unicode data files such as:
https://www.unicode.org/Public/UCD/latest/ucd/LineBreak.txt

And then supplement with:
https://www.unicode.org/Public/UCD/latest/ucd/NamedSequences.txt

**Comment by tahonermann** [comment]
The introduction of a `\N` escape sequence is technically a breaking change.  From [lex.ccon]p7 (http://eel.is/c++draft/lex.literal#lex.ccon-7):

> ... Escape sequences in which the character following the backslash is not listed in Table 8 are conditionally-supported, with implementation-defined semantics. ...

I don't expect any real breakage to occur in practice.

I *think* the proposed wording in P1097R1 would retain the current conditionally-supported, implementation-defined semantics in these cases:
```
"\N" // Missing opening brace.
"\Nx" // Missing opening brace.
"\N{blah" // Missing ending brace.
"\N{xx_xx}" // Invalid n-char-sequence.
```

Do we want to make these ill-formed?  I'm leaning towards yes.

**Comment by tahonermann** [comment]
I think we should also clarify whether these cases are allowed:
```
"\N{" "NBSP" "}" // String concatenation.

#define MAKE_N_ESCAPE(N) "\N{" #N "}"
MAKE_N_ESCAPE(NBSP) // Token concatenation.

#define MAKE_N_ESCAPE2X(N) \N{ ## N ## }
#define MAKE_N_ESCAPE2S(X) #X
#define MAKE_N_ESCAPE2(X) MAKE_N_ESCAPE2S(MAKE_N_ESCAPE2X(X))
MAKE_N_ESCAPE2(NBSP) // Token pasting.
```

(I'm not completely sure I have these test cases right).

**Comment by tahonermann** [comment]
[P1097R1](http://wg21.link/p1097r1) appeared in the post-Rapperswil mailing.  This is on track for presentation to EWG in San Diego.

**Comment by tahonermann** [comment]
@rmartinho Do you think it is worth updating the paper for the San Diego pre-meeting mailing to address the cases I mentioned in the last few comments regarding  "funny" `\N` sequences?

**Comment by rmartinho** [comment]
Yeah, I'll do that at some point.

**Comment by ThePhD** [comment]
Just to update: [p1097 was presented in San Diego](https://github.com/ThePhD/future_cxx/blob/master/papers/presentations/d1097.pdf). This is on-track to get to Core by C++20.

Consensus was formed around the form of matching proposed in the paper (case-insensitive matching). There was some comment about full LM2 matching potentially reducing the storage size for the trie/lookup structure needed to find a given Named Character Escape Sequence, but most people were repulsed by the idea of strange-looking lookups.

**Comment by tahonermann** [comment]
[P1097R2](https://wg21.link/p1097r2) was [presented to EWG in Belfast](http://wiki.edg.com/bin/view/Wg21belfast/P1097-EWG).  EWG narrowly rejected it based on lack of implementation experience and concerns regarding the impact of including the character name database in the sizes of compiler binaries.  Strong encouragement was given to come back with such details.  There was one strong opponent to the proposed design who would prefer to see a solution implemented as a library facility using a new and extensible string interpolation facility.

A paper revision is not needed that discusses implementation experience, impact to compiler deployment, and alternative design possibilities.

**Comment by tahonermann** [comment]
[P1097R2](https://wg21.link/p1097r2) has been superseded by [P2071R0](https://wg21.link/p2071r0).  Adding myself as an additional assignee.  This is now tracked by https://github.com/cplusplus/papers/issues/798.

**Comment by tahonermann** [comment]
Closing as resolved by the adoption of [P2071R2](https://wg21.link/p2071r2) for C++23. Issue #55 tracks making a similar change for C in WG14.
