### ISSUE TITLE
Uninitialized append for contiguous containers

### ISSUE THREAD

**Issue by tahonermann** [sg16-unicode/sg16#3]
Add the ability to append elements to contiguous containers (`std::vector`, `std::string`) without requiring the newly constructed elements to be unnecessarily initialized.
- Will eventually appear in https://wg21.link/p1010

**Comment by mzeren-vmw** [comment]
work in progress can be found at: https://github.com/mzeren-vmw/iso/blob/master/resize/d1010r0.bs

**Comment by tahonermann** [comment]
This issue is now tracked by https://github.com/cplusplus/papers/issues/322.

**Comment by tahonermann** [comment]
This issue no longer needs to be tracked by SG16.  Closing.
