### ISSUE TITLE
String literal concatenation in translation phase 5 and 6 contradicts [lex.string]

### ISSUE THREAD

**Issue by tahonermann** [sg16-unicode/sg16#47]
Translation phase 5 states in [[lex.phases]p5](http://eel.is/c++draft/lex.phases#1.5):
> Each source character set member in a character literal or a string literal, as well as each escape sequence and _universal-character-name_ in a character literal or a non-raw string literal, is converted to the corresponding member of the execution character set ([lex.ccon], [lex.string]); if there is no corresponding member, it is converted to an implementation-defined member other than the null (wide) character.

Translation phase 6 states in [[lex.phases]p6](http://eel.is/c++draft/lex.phases#1.6):
> Adjacent string literal tokens are concatenated.

The order of these operations contradicts [[lex.string]p12](http://eel.is/c++draft/lex.string#12) which states:
> ... If one string-literal has no encoding-prefix, it is treated as a string-literal of the same encoding-prefix as the other operand. ...

The following example is included in [table 9](http://eel.is/c++draft/lex.string#tab:lex.string.concat):

| Source | Means |
| ------ | ----- |
| `u"a"` `"b"` | `u"ab"` |

The wording in translation phases 5 and 6 does not produce the intended result in the above table since `"b"` will have already been converted to the execution character set prior to concatenation.

Clang and gcc produce the expected results according to [[lex.string]p12](http://eel.is/c++draft/lex.string#12).  However, MSVC follows translation phase 5 and 6 and first converts the ordinary string literal to the execution character set (and to '?' if not representable), and then concatenates the result encoded as UTF-16.

Additionally, when MSVC is invoked with the `/utf-8` option, The UTF-8 encoded code units in the ordinary string literal are individually interpreted according to the active code page (generally Windows-1252) and then re-encoded as UTF-16.  This appears to be a defect in the MSVC compiler.

The above differences can be observed with Compiler Explorer: https://msvc.godbolt.org/z/vBdEXq

@steve-downey requested a core issue to be filed on the core mailing list (http://lists.isocpp.org/core/2019/03/5770.php). The new issue hasn't been opened yet, but is expected to be prior to the 2019 Cologne meeting.

**Comment by tahonermann** [comment]
This is now tracked by [CWG 2455](http://www.open-std.org/jtc1/sc22/wg21/docs/cwg_active.html#2455).

If adopted, [P2314](https://wg21.link/p2314) will address this.

**Comment by dimztimz** [comment]
The paper P2314 got accepted, so what happens now with the CWG issue? Will it be pushed toward C++20?

**Comment by tahonermann** [comment]
Thank you, @dimztimz, for helping to keep our issue queue clean!

Closing this as resolved by the [adoption](https://github.com/cplusplus/papers/issues/998) of P2314 for C++23.
