### ISSUE TITLE
WG14: Make char16_t/char32_t string literals be UTF-16/32

### ISSUE THREAD

**Issue by tahonermann** [sg16-unicode/sg16#54]
[P1041](https://wg21.link/p1041) was adopted for C++20.  We should now move forward getting it adopted for C.

**Comment by ThePhD** [comment]
Draft for the next mailing. Feedback welcome.

https://thephd.github.io/_vendor/future_cxx/papers/C%20-%20char16_t%20&%20char32_t%20string%20literals%20shall%20be%20UTF-16%20&%20UTF-32.html

**Comment by tahonermann** [comment]
I briefly reviewed; looks good.

There is what looks to be two copy/paste wording issues in 3.4 
(§6.4.4.4) 
<https://thephd.github.io/_vendor/future_cxx/papers/C%20-%20char16_t%20&%20char32_t%20string%20literals%20shall%20be%20UTF-16%20&%20UTF-32.html#rewrite-6.4.4.4-character-constants-paragraph-12-and-13-and-insert-2-new-paragraphs-before-13-making-it-15>:

 1. In the wording for UTF-8 character constants, it states, "A UTF–8
    character constant has type unsigned char which is an unsigned
    integer types defined in the <uchar.h> header."  The type is right,
    but uchar.h is not involved.
 2. In the wording for the UTF-16 and UTF-32 character constants, it
    states, "A UTF–16 (UTF-32) character constant has type unsigned char
    which is an unsigned integer types defined in the <uchar.h> header. 
    This time the type is incorrect (it should be char16_t (char32_t),
    but the reference to uchar.h is right.

Tom.

**Comment by ThePhD** [comment]
Thanks for the corrections, Tom, I definitely did too much copy-pasta: https://thephd.github.io/_vendor/future_cxx/papers/C%20-%20char16_t%20&%20char32_t%20string%20literals%20shall%20be%20UTF-16%20&%20UTF-32.html

**Comment by WPMGPRoSToTeMa** [comment]
In 3.8:
`The encoding of any of wchar_t`
I think it can be replaced with:
`The encoding of wchar_t`

**Comment by tahonermann** [comment]
This issue was resolved by the adoption of [N2728 (char16_t & char32_t string literals shall be UTF-16 & UTF-32 | r0)](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2728.htm) for C23 during the August/September 2021 WG14 meeting as noted in [N2913 (Editor's Report, Post May 2022 Meeting)](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2913.htm). Closing.
