### ISSUE TITLE
What is the point of "WG14" tag?

### ISSUE THREAD

**Issue by DBJDBJ** [sg16-unicode/sg16#58]
How long is that wait going to last? 3, maybe 4 years? More?

![image](https://user-images.githubusercontent.com/145155/75151708-a0a86700-5707-11ea-8b88-eda9cd9ecc93.png)

**Comment by tahonermann** [comment]
I don't understand the question.  Regardless, filing a github issue to ask a question is not the appropriate protocol.  Please feel free to post your question either to me directly via email, on the SG16 mailing list, or in our Slack channel.  See https://github.com/sg16-unicode/sg16 for relevant links.

Closing as non-actionable.

**Comment by DBJDBJ** [comment]
@tahonermann  Sorry Tom, but I do not see the point of introducing `char8_t` as a keyword and then announcing full support for it but not before WG14 does it? 

The question is very clear. The answer might be something like: "There is a point because WG14 members are reading these issues here, and they will act accordingly..." 

In any project (in any discipline) you do not say: "Oh this building is done, it is just we are waiting for the foundations to be finished, but consider it done. Erm what, you want to enter? Well, you can but that would be UB." ...

One more thing Tom, I am not aiming at you, but it just feels futile to talk to anything which has a name with a prefix "committee", and I can see here good yourself leading, and bravely updating GCC char8_t issue too .. it seems for years now.

For the outsider all very puzzling ... I will shut up now ... Roger & Out :)

**Comment by tahonermann** [comment]
@DBJDBJ, this is not the place to discuss this.  I'm happy to answer your questions, but please send them to me either directly in email if you only want to reach me, or to the SG16 mailing list or Slack channel if you want to reach the wider group.
