### ISSUE TITLE
Character doesn't mean anything

### ISSUE THREAD

**Issue by cor3ntin** [sg16-unicode/sg16#59]
In the wording, depending on context, the term `character` can designate
- An abstract character in the source encoding
- An abstract character in the execution encoding
- A code point in the
- A code unit
- An instance of a character type (char, char8_t, charc16_t, etc), which doesn't represent a character type
- ...

More critically, this confusion is source of bugs, or unsupported feature ( for example, is it possible to have a non-ascii digital separator?)

We should fix that but its a lot of work
There is a bit of code wording to change and quite a bit of change which might be required
to `<filesystem>, <string>, <regex>, <locale>, <format>, <iostream>`

**Comment by tahonermann** [comment]
I think this is a particular case of updates that we would do for issue #7.  Can you provide a rationale for keeping this issue open as a separate task?

**Comment by tahonermann** [comment]
Closing as something to be addressed as part of https://github.com/sg16-unicode/sg16/issues/7.
