### ISSUE TITLE
Specify that char16_t and char32_t literals are UTF-16 and UTF-32 respectively

### ISSUE THREAD

**Issue by tahonermann** [sg16-unicode/sg16#6]
The C and C++ standards do not currently specify that the encoding of `char16_t` and `char32_t` literals are respectively UTF-16 and UTF-32. C states that they are only if the corresponding `STDC_UTF_16` or `STDC_UTF_32` macro is defined to 1 (6.10.8.2, "Environment macros"). Various parts of the C++ standard (`codecvt` and `char_traits`) refer to UTF-16/UTF-32 thereby admitting a bias towards these encodings despite lack of strict specification.

It may be that, in practice, all C and C++ compilers that are being updated to conform to new standards, are only using UTF-16 and UTF-32 for these literals. If so, the standards can be updated to mandate the use of these encodings.

**Comment by tahonermann** [comment]
Status of this issue: [P1041R1](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2018/p1041r1.html) appeared in the post-Rapperswil mailing.  With a little luck, it will be presented to EWG in San Diego.

**Comment by ThePhD** [comment]
Side note: it was decided that for the `__STD_C...` macros related to UTF16/32, those could be handled as editorial / Defect Reports in Core, and did not have to be necessarily apart of this proposal.

**Comment by tahonermann** [comment]
Oh, hey, there are a few relevant core issues:
- [CWG 1859](http://wg21.link/cwg1859) - UTF-16 in char16_t string literals 
- [CWG 1802](http://wg21.link/cwg1802) - char16_t string literals and surrogate pairs

**Comment by tahonermann** [comment]
This issue was resolved by the adoption of [P1041R4](https://wg21.link/p1041r4) in Kona.  Closing.
