### ISSUE TITLE
Consider support for non-identifier characters in UDL suffixes (CWG #1871)

### ISSUE THREAD

**Issue by tahonermann** [sg16-unicode/sg16#61]
JF requested that SG16 consider this issue and provide a recommendation to EWG.

[CWG issue 1871](https://wg21.link/cwg1871) tracks a request to allow the use of non-identifier characters, specifically currency symbols, as UDL suffixes.

**Comment by ThePhD** [comment]
As in, `_$` and `_¥` are seen as an identifier (`_`) and then a separate non-identifier?

Do we have places where `_` and `$` are already pre-existing?

**Comment by jensmaurer** [comment]
The (abstract) request is that "_$" and "_€" should be valid suffixes for user-defined literals. It is believed that currency symbols are not valid identifier characters at this time and in a TR31-enabled future. Suggesting to use ISO currency codes (e.g. _USD and _EUR) and saying "no" to the request is a reasonable response, in my view.

**Comment by tahonermann** [comment]
The following messages on the CWG mailing list are relevant:
- https://listarchives.isocpp.org/cgi-bin/wg21/message?wg=core&msg=24712
- https://listarchives.isocpp.org/cgi-bin/wg21/message?wg=core&msg=24713
- https://listarchives.isocpp.org/cgi-bin/wg21/message?wg=core&msg=24714
- https://listarchives.isocpp.org/cgi-bin/wg21/message?wg=core&msg=24716
- https://listarchives.isocpp.org/cgi-bin/wg21/message?wg=core&msg=24717
- https://listarchives.isocpp.org/cgi-bin/wg21/message?wg=core&msg=24719

(Oh, and the progressive encoding corruption through those messages is entertaining!  The first message contains `_=C2=A2`, but that soon becomes `_ï¿½ï¿½`, and then progresses to `ï¿½ï¿½ï¿½ï¿½`)

**Comment by tahonermann** [comment]
SG16 discussed this issue at its [April 22nd, 2020 telecon](https://github.com/sg16-unicode/sg16-meetings#april-22nd-2020).  The following poll was performed:

**Poll: Is there any objection to unanimous consent for recommending rejection of this proposal?**
- **No objection to unanimous consent.**

The SG16 recommendation has been communicated to the EWG chair.

Closing this issue.
