### ISSUE TITLE
WG14 N2594: Disallow mixed string literal concatenation

### ISSUE THREAD

**Issue by tahonermann** [sg16-unicode/sg16#62]
[P2201](https://wg21.link/p2201) appears to be on track for adoption in C++23.  @ThePhD has submitted [N2594](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2594.htm) for WG14.

**Comment by ThePhD** [comment]
This has been integrated into the C2x standard: http://www.open-std.org/jtc1/sc22/wg14/www/docs/n2596.pdf

§6.4.5, paragraph 2, Constraints
