### ISSUE TITLE
WG21 P1859: Modern terminology updates 

### ISSUE THREAD

**Issue by tahonermann** [sg16-unicode/sg16#7]
The C++ standard currently uses the term "character" to refer to both code units and code points and "character set" where character encoding is intended. The lack of proper terminology leads to defective interfaces (e.g., `std::ctype<>::toupper`). Future library additions for Unicode will depend on modern terminology for clear and correct specification.

**Comment by cubbimew** [comment]
> "character set" where character encoding is intended 

Does it really work for character sets? The ones described in [[lex.charset]](http://eel.is/c++draft/lex.charset) appear to be literally sets (of code points): "The basic source character set consists of 96 characters..."

If anything, the encoding would come up when the footnote under that says "an implementation is required to document how the basic source characters are represented in source files"

**Comment by tahonermann** [comment]
Many of the existing uses of "character set" are appropriate.  In some places, use of character encoding would be more correct or clear.  In a few cases, the terms are used inconsistently.  For example, http://eel.is/c++draft/locale.codecvt#3.

**Comment by tahonermann** [comment]
[P1859](https://wg21.link/p1859) now tracks this issue.  R0 was [discussed in Belfast](http://wiki.edg.com/bin/view/Wg21belfast/SG16P1859R0).  Now awaiting an updated paper.

**Comment by tahonermann** [comment]
This issue is now tracked by https://github.com/cplusplus/papers/issues/613.

**Comment by dimztimz** [comment]
The readme should be edited and the paper should be moved to the section Inactive papers and noted that it got replaced. This issue should be closed.

**Comment by tahonermann** [comment]
Agreed, thank you, @dimztimz! Done!
