### ISSUE TITLE
Explicitly disallow unnamed Unicode codepoints in http://eel.is/c++draft/lex.charset#2

### ISSUE THREAD

**Issue by tahonermann** [sg16-unicode/sg16#8]
http://eel.is/c++draft/lex.charset#2
Says:

> The character designated by the universal-character-name \UNNNNNNNN is that character whose character short name in ISO/IEC 10646 is NNNNNNNN; the character designated by the universal-character-name \uNNNN is that character whose character short name in ISO/IEC 10646 is 0000NNNN. If the hexadecimal value for a universal-character-name corresponds to a surrogate code point (in the range 0xD800–0xDFFF, inclusive), the program is ill-formed.

Should it also say:

> If the hexadecimal value for a universal-character-name is not named by ISO/IEC 10646 then the program is ill-formed

Or is that implied?

**Comment by rmartinho** [comment]
After some review, I have the feeling this stems from an outdated 10646 version. The current version doesn't have a "short name" concept (well, except for jamo short names, but that's clearly not the intention here). There's a "short identifier" concept (in 6.5) but that cannot be more than six digits (the familiar U+ syntax). I propose the following.

> The character designated by the universal-character-name \U00NNNNNN is that character whose code point short identifier in ISO/IEC 10646 is U+NNNNNN; the character designated by the universal-character-name \uNNNN is that character whose code point short identifier in ISO/IEC 10646 is U+NNNN. If the hexadecimal value for a universal-character-name corresponds to a surrogate code point (in the range 0xD800–0xDFFF, inclusive), the program is ill-formed. If a universal-character-name has any other hexadecimal value, the program is ill-formed.

**Comment by rmartinho** [comment]
At Rapperswil I discussed this issue with people from Core and it was agreed that we the current wording will be fixed editorially.

**Comment by tahonermann** [comment]
That's good.  I think the right process is to submit a PR to https://github.com/cplusplus/draft.  Anyone want to volunteer to do so?

**Comment by rmartinho** [comment]
I can do that.

**Comment by rmartinho** [comment]
This PR https://github.com/cplusplus/draft/pull/2201 will be merged fixing the "short name" issue. As discussed with Jens, I will write a short paper to clean up the wording there and clarify the nonexistent code point case.

**Comment by tahonermann** [comment]
@rmartinho I think this issue is complete, yes?

**Comment by tahonermann** [comment]
> @rmartinho I think this issue is complete, yes?

Ah, no, this isn't complete yet.  The accepted editorial PR only addressed the "short name" vs "short identifier" terminology issue.  Martinho's draft [D1139](https://github.com/sg16-unicode/sg16/blob/master/papers/d1139r0.md) (which I think is yet to be submitted to a mailing) addresses the concern tracked by this issue.

**Comment by tahonermann** [comment]
Closing this issue as resolved following the adoption of [P1139R2](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2019/p1139r2.html) in Kona.
